### PR TITLE
39 sign up completed

### PR DESCRIPTION
**Pull request by tasnimalhallak**

### CODE REVIEW

**Review by halilibrahimcelik — COMMENTED** [review]
`<Route path="/Signup" element={<Signup />} />`  you shouldnt give path with upperCase and also sign-in and sign-up buttons are not navigating user to  login or register page

**Comment by halilibrahimcelik** [comment]
chrome_fRi0fFlWMR you should give  some margin to  "already a member" text

**Comment by halilibrahimcelik** [comment]
and also sign-in button's style should be fixed

**Comment by tasnimalhallak** [comment]
done

**Pull request closed without merging**
